version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: amos
      POSTGRES_PASSWORD: irembo24
      POSTGRES_DB: irembo
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "amos"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: yandex/clickhouse-server
    build:
      context: ./clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - postgres
      - kafka
      - clickhouse
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: irembo
      POSTGRES_USER: amos
      POSTGRES_PASSWORD: irembo24
      KAFKA_BROKER: kafka:9092
      CLICKHOUSE_HOST: clickhouse
    ports:
      - 8000:8000
    command: ["python", "generate_and_insert_records.py"]
