version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: amos
      POSTGRES_PASSWORD: irembo24
      POSTGRES_DB: irembo
    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "amos"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
   

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:
      - zookeeper
   

  clickhouse:
    image: yandex/clickhouse-server


  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - postgres
      - kafka
      - clickhouse
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: irembo
      POSTGRES_USER: amos
      POSTGRES_PASSWORD: irembo24
      KAFKA_BROKER: kafka:9092
      CLICKHOUSE_HOST: clickhouse
    ports:
      - 8000:8000
    command: ["sh","-c", "python generate_and_insert_records.py && python clickhouse_publisher.py"]
