name: CI Irembo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432
          - 9092:9092
          - 8123:8123
          - 9000:9000
        env:
          POSTGRES_USER: amos
          POSTGRES_PASSWORD: irembo24
          POSTGRES_DB: irembo
        volumes:
          - /var/run/docker.sock://var/run/docker.sock 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache 
        key: ${{ runner.os}}-buildx-${{github.sha}}
        restore-keys: |
          ${{runner.os}}-}-buildx-

    - name: Log into Doker Hub
      uses: docker/build-push-action@v1
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin 

    - name: Build and push
      run: docker-compose -f docker-compose.yml up --build --exit-code-from app

    - name: Run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit -- build
